@echo off
echo Inicializando repositorio git...
git init
echo Agregando archivos...
git add .
echo Creando commit inicial...
git commit -m "feat: Initial NetBreaker v3.0 public assets"
echo Configurando rama main...
git branch -M main
echo Configurando remoto...
git remote add origin https://github.com/jhosuehag/NetBreaker.git
git remote set-url origin https://github.com/jhosuehag/NetBreaker.git
echo Subiendo a GitHub...
git push -u origin main
echo Completado.
pause
